DelegatesFileUploader/Controllers/ActivitiesController.cs
using CsvHelper;
using DelegatesFileUploader.Convertions;
using DelegatesFileUploader.Data;
using DelegatesFileUploader.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace DelegatesFileUploader.Controllers
{
    public class ActivitiesController : Controller
    {
        private readonly DelegatesContext _context;
        private readonly IConfiguration _configuration;

        public ActivitiesController(DelegatesContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        
        public IActionResult Index()
        {
            var result = new DelegatesViewModel
            {
                LastChangeDate = _context.Importations.Where(i => i.Type == ImportationTypes.Activities).DefaultIfEmpty().Max(i => i.DateTime)
            };

            return View(result);
        }



        [HttpPost]
        public async Task<IActionResult> Index([Required]IFormFile file, [Required]string password)
        {

            if (password != _configuration.GetValue<string>("UploadPassword"))
                return Unauthorized("No autorizado");

            var result = new DelegatesViewModel();

            try
            {
                IEnumerable<Activity> activities = null;

                using (var stream = file.OpenReadStream())
                using (var reader = new StreamReader(stream))
                using (var csv = new CsvReader(reader))
                {
                    csv.Configuration.Delimiter = ";";
                    csv.Configuration.RegisterClassMap<ActivityMap>();
                    activities = csv.GetRecords<Activity>().ToList();
                }

                var deletedActivitiesCount = await _context.DeleteAllActivitiesAsync();
                await _context.Activities.AddRangeAsync(activities);



                var importation = new Importation
                {
                    DateTime = DateTime.Now,
                    FileName = file.FileName,
                    RowCount = activities.Count(),
                    SizeMB = Utils.ConvertBytesToMegabytes(file.Length),
                    Type = ImportationTypes.Activities
                };

                await _context.Importations.AddAsync(importation);

                await _context.SaveChangesAsync();

                result.SuccessfulMessage = $"Se agregaron {activities.Count()} registros de actividades.";

            }
            catch (Exception ex)
            {
                result.ErrorMessage = ex.Message + ex.InnerException?.Message;
            }


            result.Init = false;
            return View(result);
        }

    }
}

DelegatesFileUploader/Controllers/FlightsController.cs
using DelegatesFileUploader.Data;
using DelegatesFileUploader.Models;
using DelegatesFileUploader.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace DelegatesFileUploader.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class FlightsController : Controller
    {
        private readonly DelegatesContext _context;
        private readonly IConfiguration _configuration;
        private readonly IFlightUpdater _flightStatusUpdater;

        public FlightsController(DelegatesContext context,
            IFlightUpdater flightStatusUpdater,
            IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
            _flightStatusUpdater = flightStatusUpdater;
        }

        public IActionResult Index()
        {
            var result = new FlightsViewModel
            {
                InitialDate = DateTime.Today
            };

            return View(result);
        }


        [HttpPost("update")]
        public async Task<IActionResult> UpdateFligthsAsync([Required,FromBody]FlightsViewModel model)
        {
            if (model.Password != _configuration.GetValue<string>("UploadPassword"))
                return Unauthorized("No autorizado");

            await _flightStatusUpdater.UpdateFlightsAsync(model.InitialDate);

            return NoContent();
        }

    }
}

DelegatesFileUploader/Controllers/SpecialRoomingController.cs
using DelegatesFileUploader.Convertions;
using DelegatesFileUploader.Data;
using DelegatesFileUploader.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using NPOI.SS.UserModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace DelegatesFileUploader.Controllers
{
    public class SpecialRoomingController : Controller
    {
        class SpecialRoomingAccommodation
        {
            public string Name { get; set; }
            public string Address { get; set; }
            public string Coordinates { get; set; }
        }


        private readonly DelegatesContext _context;
        private readonly IConfiguration _configuration;

        public SpecialRoomingController(DelegatesContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            var result = new DelegatesViewModel
            {
                LastChangeDate = _context.Importations.Where(i => i.Type == ImportationTypes.SpecialRooming).DefaultIfEmpty().Max(i => i.DateTime)
            };

            return View(result);
        }



        [HttpPost]
        public async Task<IActionResult> Index([Required]IFormFile file, [Required]string password)
        {

            if (password != _configuration.GetValue<string>("UploadPassword"))
                return Unauthorized("No autorizado");

            var result = new DelegatesViewModel();

            try
            {
                

                ISheet sheet;
                using (var stream = file.OpenReadStream())
                {

                    var wb = WorkbookFactory.Create(stream);
                    sheet = wb.GetSheetAt(0);
                }

                var specialRommingList = new List<SpecialRooming>();

                

                for (int i = 1; i < sheet.PhysicalNumberOfRows; i++)
                {
                    try
                    {

                        var specialRooming = sheet.GetRow(i).GetSpecialRooming();
                        if (specialRooming == null)
                            break;
                        specialRommingList.Add(specialRooming);

                    }
                    catch (Exception ex)
                    {
                        throw;
                    }
                }

                var specialRommingAccommodations = specialRommingList.GroupBy(r => r.AccommodationName).Select(g =>
                new SpecialRoomingAccommodation
                {
                    Name = g.Key,
                    Address = g.FirstOrDefault().AccomodationAddress,
                    Coordinates = g.FirstOrDefault().AccommodationCoordinates
                }).ToList();

                var accomodations = _context.Accommodations.ToList();

                var newAccomodations = new List<Accommodation>();
                
                foreach (var item in specialRommingAccommodations)
                {
                    if (!String.IsNullOrEmpty(item.Name))
                    {

                        var accomodation = accomodations.FirstOrDefault(a => a.Name == item.Name);
                        if (accomodation == null)
                        {
                            accomodation = new Accommodation()
                            {
                                Name = item.Name,
                                Type = AccommodationTypes.Private
                            };
                            newAccomodations.Add(accomodation);
                        }
                        accomodation.Address = item.Address;
                        if (!string.IsNullOrEmpty(item.Coordinates) && item.Coordinates.Contains(','))
                        {
                            var array = item.Coordinates.Split(',');
                            accomodation.Latitude = double.Parse(array[0], CultureInfo.InvariantCulture);
                            accomodation.Longitude = double.Parse(array[1], CultureInfo.InvariantCulture);
                        }
                    }
                }

                await _context.Accommodations.AddRangeAsync(newAccomodations);
                accomodations = _context.Accommodations.ToList();
                accomodations = accomodations.Union(newAccomodations).Distinct().ToList();

                foreach (SpecialRooming item in specialRommingList)
                {
                    var del = _context.Delegates.FirstOrDefault(d => d.ApplicantNo == item.ApplicantNo);
                    if (del == null)
                        throw new Exception("Delegado no encontrado " + item.ApplicantNo);

                    if (!String.IsNullOrWhiteSpace(item.AccommodationName))
                    {

                        del.Accommodation = accomodations.FirstOrDefault(a => a.Name == item.AccommodationName);


                        if (del.Accommodation != null)
                        {
                            del.SpecialRoomingPrivateAccommodation = del.Accommodation.Type == AccommodationTypes.Private;
                        }
                    }
                    
                    
                }

                var importation = new Importation
                {
                    DateTime = DateTime.Now,
                    FileName = file.FileName,
                    RowCount = sheet.PhysicalNumberOfRows,
                    SizeMB = Utils.ConvertBytesToMegabytes(file.Length),
                    Type = ImportationTypes.SpecialRooming
                };

                await _context.Importations.AddAsync(importation);

                await _context.SaveChangesAsync();

                result.SuccessfulMessage = $"Se agregaron {newAccomodations.Count} alojamientos especiales";


            }
            catch (Exception ex)
            {
                result.ErrorMessage = ex.Message + ex.InnerException?.Message;
            }


            result.Init = false;
            return View(result);
        }

    }
}

DelegatesFileUploader/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DelegatesFileUploader</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

            <a class="navbar-brand" href="#">IC BA2019</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Delegados <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Activities" asp-action="Index">Actividades</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="SpecialRooming" asp-action="Index">Alojamiento especial</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Flights" asp-action="Index">Vuelos</a>
                    </li>
                </ul>
                <a class="btn btn-outline-success my-2 my-sm-0" href="https://gitlab.com/zeqk/delegatesfileuploader">Source code</a>                
            </div>
        </nav>
    </header>
    <div class="container">
        @*<partial name="_CookieConsentPartial" />*@
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - DelegatesFileUploader
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>